# Generated by Django 4.2.11 on 2025-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_activity_log_and_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'Админ'), ('storekeeper', 'Кладовщик'), ('cashier', 'Кассир'), ('accountant', 'Бухгалтер')], default='storekeeper', max_length=50),
        ),
    ]
