# Generated by Django 4.2.11 on 2025-12-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stock_allow_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('kaspi', 'Kaspi'), ('halyk', 'Halyk'), ('cash', 'Наличные'), ('mixed', 'Смешанная'), ('delayed', 'Отложка')], max_length=10),
        ),
    ]
